"""Strict command schema, fixed safety review, and ToolMessage encoding."""

from __future__ import annotations

import re
from dataclasses import dataclass

from langchain_core.messages import ToolMessage

from .contracts import CommandToolEnvelope, ExecuteCommandArguments


DANGEROUS_COMMAND_PATTERN = re.compile(
    r"(?:"
    r"\brm\s+-rf\s+/"
    r"|\bdd\s+if="
    r"|\bmkfs\."
    r"|:\(\)\s*\{"
    r"|>\s*/dev/sd"
    r"|\bchmod\s+-R\s+777\s+/"
    r")",
    re.IGNORECASE,
)


class CommandRejected(RuntimeError):
    """Carry a stable code when the approved direct-danger regex matches."""

    def __init__(self, error_code: str, message: str) -> None:
        """Store the public code and reason without embedding the raw command."""

        super().__init__(f"{error_code}: {message}")
        self.error_code = error_code  # Stable code consumed by the graph tool node.
        self.safe_message = message  # Reviewed reason without command text.


class CommandSafetyReviewer:
    """Apply the single approved regex directly to the original command text."""

    def review(self, command: str) -> None:
        """Reject a direct match without trim, normalization, parsing, or expansion."""

        if DANGEROUS_COMMAND_PATTERN.search(command) is not None:
            raise CommandRejected(
                "COMMAND_REJECTED_DANGEROUS_PATTERN",
                "the command matched the direct-danger safety policy",
            )


def tool_message(tool_call_id: str, envelope: CommandToolEnvelope) -> ToolMessage:
    """Pair a canonical JSON envelope with its original model tool call ID."""

    return ToolMessage(
        content=envelope.model_dump_json(),
        tool_call_id=tool_call_id,
    )


@dataclass(frozen=True, slots=True)
class ExecuteCommandToolDefinition:
    """Describe the only model-facing Tool without choosing a Provider protocol."""

    name: str  # Stable function name accepted by the Agent graph.
    description: str  # Reviewed model-facing capability and timeout description.
    parameters: dict[str, object]  # Strict JSON Schema generated by Pydantic.
    strict: bool  # Require Provider-side schema enforcement when supported.


def build_execute_command_tool_definition() -> ExecuteCommandToolDefinition:
    """Build the canonical execute_command definition for either model API."""

    return ExecuteCommandToolDefinition(
        name="execute_command",
        description=(
            "Execute one complete shell command on the SSH session bound to this "
            "agent run. The command can modify remote state and has a 30-second "
            "execution timeout."
        ),
        parameters=ExecuteCommandArguments.model_json_schema(),
        strict=True,
    )
